# Generated by Django 4.2.16 on 2026-03-13 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.TextField()),
                ('original_meta', models.TextField()),
                ('original_content', models.TextField()),
                ('suggested_title', models.TextField()),
                ('suggested_meta', models.TextField()),
                ('suggested_content', models.TextField()),
                ('final_title', models.TextField(blank=True, null=True)),
                ('final_meta', models.TextField(blank=True, null=True)),
                ('final_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('edited', 'Edited'), ('approved', 'Approved'), ('applied', 'Applied')], default='generated', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
