# Generated by Django 4.2.16 on 2026-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_optimizer', '0001_initial'),
        ('pages', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentoptimization',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
        migrations.AddField(
            model_name='contentoptimization',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
    ]
