# Generated by Django 4.2.16 on 2026-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('websites', '0001_initial'),
        ('seo_audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoaudit',
            old_name='checked_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='score',
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='cloudflare_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='has_h1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='images_missing_alt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='is_accessible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='seo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='total_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='websites.website'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
