# Generated by Django 4.2.16 on 2026-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_speed', models.FloatField(help_text='Seconds')),
                ('seo_score', models.IntegerField()),
                ('status', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='websites.website')),
            ],
        ),
    ]
