# Generated by Django 4.2.16 on 2026-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('backlinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlink',
            old_name='link',
            new_name='url',
        ),
        migrations.AddField(
            model_name='backlink',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backlink',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('broken', 'Broken')], max_length=20),
        ),
        migrations.AlterField(
            model_name='backlink',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='websites.website'),
        ),
    ]
